# MLP Assignment By-Amandeep Singh Jagde

In [1]:
import numpy as np;
import pandas as pd;

In [2]:
#Aa
data = pd.read_csv("wine.csv",  names=[ "A","B","C","D","E","F","G","H","I","J","K","L","M","N"])

In [3]:
data.head()

A      B     C     D     E    F     G     H     I     J     K     L     M  \
0  1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

      N  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [4]:
#B
from sklearn.model_selection import train_test_split

In [5]:
data=pd.DataFrame(data)


In [6]:
data["A"].value_counts()

2    71
1    59
3    48
Name: A, dtype: int64

In [7]:
y = data["A"]

In [8]:
X=data.iloc[:, 1:]

In [9]:
X

B     C     D     E    F     G     H     I     J      K     L     M  \
0    14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04  3.92   
1    13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05  3.40   
2    13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03  3.17   
3    14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86  3.45   
4    13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04  2.93   
..     ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   ...   
173  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64  1.74   
174  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70  1.56   
175  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59  1.56   
176  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60  1.62   
177  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61  1.60   

        N  
0    1065  
1    1050  
2    1185  
3    1480  
4     735  
..    ...  
173   740  
174   750  
175   835  
176   840  
177   560  

[178 rows x 13 columns]

In [10]:
 X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [11]:
X_train.shape

(119, 13)

In [12]:
y_train.shape

(119,)

In [13]:
#B. a
from sklearn.preprocessing import StandardScaler

In [14]:
scaler= StandardScaler()
scaler.fit(X_train)
#B. b
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
from sklearn.neural_network import MLPClassifier

In [17]:
#B. c
#making three layers with differnet neuron
mlp = MLPClassifier(hidden_layer_sizes=(30,15,6))

In [18]:
#B.d
mlp.fit(X_train,y_train)

/Users/amandeep/opt/anaconda3/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(30, 15, 6))

In [19]:
#C.a
predictions = mlp.predict(X_test)

In [20]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[20  0  0]
 [ 1 23  0]
 [ 0  0 15]]


In [21]:
#C. b
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           1       0.95      1.00      0.98        20
           2       1.00      0.96      0.98        24
           3       1.00      1.00      1.00        15

    accuracy                           0.98        59
   macro avg       0.98      0.99      0.98        59
weighted avg       0.98      0.98      0.98        59

